### ISSUE TITLE
Create a cerca with all the postal codes

### ISSUE THREAD

**Issue by wballard** [glg/homeless-helper#4]
Comment on this with an URL query sample that takes the country and partially typed postal code, returning an autocomplete array of all the fields.

**Comment by wballard** [comment]
Ohh -- and these folks won't be logging in with GLG accounts, though will be GLG interns, so we'll need an .htpasswd or a service account in AD passed as credentials.

**Comment by jimclouse** [comment]
cerca index helper_postal_codes now exists

**Comment by wballard** [comment]
you have a sample query URL

**Comment by jimclouse** [comment]
This will do a basic search:
url: east.glgresearch.com/cerca-3D9FA02/
POST helper_postal_codes/_search
{
   "query": {
       "match": {
           "postalCode": "<entry>"
       }
   }
}
